sonar.projectKey=tediyo_Integrating-Github-Actions-to-Sample-registartion-Functionality
sonar.organization=tediyo

sonar.sources=apps

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**

sonar.javascript.lcov.reportPaths=apps/backend/coverage/lcov.info,apps/frontend/coverage/lcov.info
sonar.qualitygate.wait=true